# mpv build config for iOS arm64
ENABLE_LIBMPV_SHARED=no
ENABLE_LIBMPV_STATIC=yes
ENABLE_LIBASS=yes
ENABLE_LIBPLACEBO=yes
ENABLE_LIBDAV1D=yes
ENABLE_GL=no
ENABLE_VIDEOTOOLBOX=yes
ENABLE_GNUTLS=yes
ENABLE_FONTCONFIG=yes
ENABLE_FRIBIDI=yes
ENABLE_HARFBUZZ=yes
TARGET_OS=iOS
TARGET_ARCH=arm64
