// AUTO-GENERATED by scripts/inline-polyfill.mjs -- DO NOT EDIT
// Source: overlay/src/node/polyfills.js (POLYFILL_SOURCE function)
// Regenerate: node scripts/inline-polyfill.mjs

export const polyfillCode = `function POLYFILL_SOURCE() {

// 日志桥：向 RN 发送日志消息（显示在 Boot 页面的日志框里）
// 同时暴露到全局，供注入的 bundle 代码使用
var _log = function (m) { try { window.ReactNativeWebView?.postMessage(JSON.stringify({ type: 'log', msg: '[WV] ' + m })); } catch (e) {} };
window._log = _log;

_log('polyfill start');

// ============================================================
// 0. 全局 polyfill
// ============================================================
globalThis.global = globalThis;
globalThis.process = globalThis.process || {
    env: { NODE_ENV: 'production', NODE_PATH: '/data', DEV_HTTP_PORT: '0', CI: undefined, DEBUG: undefined, HTTPS_PROXY: undefined, HTTP_PROXY: undefined, JEST_WORKER_ID: undefined, NODE_DEBUG: undefined, NODE_V8_COVERAGE: undefined, NO_PROXY: undefined, UNDICI_NO_FG: undefined, http_proxy: undefined, https_proxy: undefined, no_proxy: undefined },
    cwd: () => '/',
    nextTick: (fn, ...args) => setTimeout(() => fn(...args), 0),
    version: 'v18.20.4',
    versions: { node: '18.20.4', v8: '11.3', modules: '108', icu: '72.1' },
    platform: 'darwin',
    arch: 'arm64',
    argv: ['node', 'main.js'],
    exit: () => {},
    stdout: { write: (s) => { console.log(s); } },
    stderr: { write: (s) => { console.error(s); } },
    // [Symbol.toStringTag] 使 Object.prototype.toString.call(process) 返回 '[object process]'
    // 这对于 axois 等库检测 Node.js 环境至关重要。
    // 如果缺失，axios 会认为当前是浏览器环境，使用 XMLHttpRequest 适配器，
    // 导致 HTTP 请求直接从 WebView 发出，绕过 proxy，遇到 CORS 限制时失败（ERR_NETWORK）。
    [Symbol.toStringTag]: 'process',
};
// 禁用 XMLHttpRequest 以强制 axios 等库使用 Node.js http 适配器。
// 在 WebView 中 XMLHttpRequest 可用，axios 会优先选择它而非 http.request，
// 导致 HTTP 请求直接从 WebView 的浏览器引擎发出，遇到 CORS/SSL 限制。
// 保存原始引用以备 polyfill 内部 fallback 使用。
var _origXMLHttpRequest = globalThis.XMLHttpRequest;
globalThis.XMLHttpRequest = undefined;
try { window.XMLHttpRequest = undefined; } catch(e) {}
try { globalThis.XMLHttpRequest = undefined; } catch(e) {}
    hrtime: (() => {
        const _origin = (typeof performance !== 'undefined' ? performance : Date).now();
        const fn = (prev) => {
            const now = (typeof performance !== 'undefined' ? performance : Date).now() - _origin;
            const sec = Math.floor(now / 1000);
            const ns = Math.floor((now % 1000) * 1e6);
            if (prev) return [sec - prev[0], ns - prev[1]];
            return [sec, ns];
        };
        fn.bigint = () => BigInt(Math.floor(((typeof performance !== 'undefined' ? performance : Date).now() - _origin) * 1e6));
        return fn;
    })(),
}`;
